return function()
    https = require 'https'
    utf8 = require 'utf8'
    g3d = require 'libraries.g3d'
    lollipop = require 'libraries.lollipop'
    neuron = require 'libraries.neuron'
    loveframes = require 'libraries.loveframes'
    lovedownloader = require 'libraries.lovedownloader'
    lua2xml = require 'libraries.xml2lua'
    moonshine = require 'libraries.moonshine'
    slab = require 'libraries.slab'
    suit = require 'libraries.suit'
    class = require 'libraries.classic'
    camera = require 'libraries.camera'
    collision = require 'libraries.collision'
    deep = require 'libraries.deep'
    discordrpc = require 'libraries.discordRPC'
    gamestate = require 'libraries.gamestate'
    gamejolt = require 'libraries.gamejolt'
    flux = require 'libraries.flux'
    knifeevent = require 'libraries.knifeevent'
    json = require 'libraries.json'
    luafft = require 'libraries.luafft'
    lume = require 'libraries.lume'
    nativefs = require 'libraries.nativefs'
    timer = require 'libraries.timer'
end